spring.application.name=semantic-search-service
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5432/semantic_search
spring.datasource.username=semantic
spring.datasource.password=semantic

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate


openai.apiKey=${OPENAI_API_KEY}
openai.embeddingModel=${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}
